### ISSUE TITLE
Bitmovin Android Proguard Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#11]
While creating release build I am getting these warnings.
Which is related to proguard. Please provide the solution

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. |  
-- | --
com.bitmovin.player.c: can't find superclass or interface com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.services.a.f$7: can't find superclass or interface com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.services.a.g$1: can't find superclass or interface com.google.ads.interactivemedia.v3.api.player.ContentProgressProvider |  
com.bitmovin.player.services.a.g$2: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdsLoader$AdsLoadedListener |  
com.bitmovin.player.services.a.g$3: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.h$7: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.h$8: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j$1: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j$2: can't find superclass or interface com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.c: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoProgressUpdate |  
com.bitmovin.player.c: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoProgressUpdate |  
com.bitmovin.player.c$1: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$1: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c$1: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$2: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$2: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c$2: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$3: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$3: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c$3: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$5: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$5: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c$5: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$6: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.c$6: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.c$6: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.services.a.f: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.services.a.f: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.services.a.f: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkFactory |  
com.bitmovin.player.services.a.f: can't find referenced class com.google.ads.interactivemedia.v3.api.AdDisplayContainer |  
com.bitmovin.player.services.a.f: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.services.a.f$7: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer$VideoAdPlayerCallback |  
com.bitmovin.player.services.a.f$7: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoAdPlayer |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader$AdsLoadedListener |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkFactory |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkSettings |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdDisplayContainer |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkSettings |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkFactory |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.ImaSdkFactory |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsRequest |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsRequest |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdError |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdDisplayContainer |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.player.ContentProgressProvider |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader$AdsLoadedListener |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdDisplayContainer |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdError |  
com.bitmovin.player.services.a.g: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g$1: can't find referenced class com.google.ads.interactivemedia.v3.api.player.ContentProgressProvider |  
com.bitmovin.player.services.a.g$1: can't find referenced class com.google.ads.interactivemedia.v3.api.player.VideoProgressUpdate |  
com.bitmovin.player.services.a.g$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader$AdsLoadedListener |  
com.bitmovin.player.services.a.g$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.g$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManagerLoadedEvent |  
com.bitmovin.player.services.a.g$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.g$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManagerLoadedEvent |  
com.bitmovin.player.services.a.g$3: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.g$3: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.g$4: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsLoader |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.Ad |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdError |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.Ad |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdError |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.h: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h$6: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.h$7: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.h$7: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.h$8: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.h$8: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h$9: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.h$9: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.h$9: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j: can't find referenced class com.google.ads.interactivemedia.v3.api.AdsManager |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventListener |  
com.bitmovin.player.services.a.j$1: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.j$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.j$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent$AdErrorListener |  
com.bitmovin.player.services.a.j$2: can't find referenced class com.google.ads.interactivemedia.v3.api.AdErrorEvent |  
com.bitmovin.player.services.a.j$3: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.bitmovin.player.services.a.j$3: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent |  
com.bitmovin.player.services.a.j$3: can't find referenced class com.google.ads.interactivemedia.v3.api.AdEvent$AdEventType |  
com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter: can't find referenced method 'void addVideoListener(com.google.android.exoplayer2.SimpleExoPlayer$VideoListener)' in program class com.google.android.exoplayer2.SimpleExoPlayer |  
com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter: can't find referenced method 'void removeVideoListener(com.google.android.exoplayer2.SimpleExoPlayer$VideoListener)' in program class com.google.android.exoplayer2.SimpleExoPlayer |  
com.google.android.exoplayer2.ext.leanback.LeanbackPlayerAdapter$ComponentListener: can't find referenced method 'android.util.Pair getErrorMessage(java.lang.Exception)' in program class com.google.android.exoplayer2.util.ErrorMessageProvider |  
org.slf4j.LoggerFactory: can't find referenced class org.slf4j.impl.StaticLoggerBinder |  
org.slf4j.MDC: can't find referenced class org.slf4j.impl.StaticMDCBinder |  
org.slf4j.MarkerFactory: can't find referenced class org.slf4j.impl.StaticMarkerBinder |  
there were 217 unresolved references to classes or interfaces. |  
there were 3 unresolved references to program class members. |  
Exception while processing task java.io.IOException: Please correct the above warnings first. |

**Comment by hawk23** [comment]
Is this still an issue or could you resolve this in the meantime? If the issue still persists, please provide us more information about your project setup:
- Which libraries and dependencies are you including into the app project?
- Which proguard rules are you using?

**Comment by SInCE** [comment]
Hi, thanks for reaching out! 

As there is no further activity, I assume you are no longer facing this particular problem. Therefore, I'm closing this issue.

If this isn't the case, **please reach out** using our official customer channels, either through the chat in your dashboard at https://bitmovin.com/dashboard or **via email** at support@bitmovin.com. Thank you very much for your understanding!
