### ISSUE TITLE
On Pip close Audio plays in Background

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#19]
When a video enters a PIP state. I am able to see two controls which are expand and close.
In expand the PIP state goes back to full screen Activity but on close of PIP the audio still plays in background.
Please check the sample and update or Is there any access to the controls of PiP?

**Comment by matamegger** [comment]
Thank you for reporting! Our team has found the reason and we will include a fix in an upcoming release of the SDK. Also the samples will be updated accordingly.

In the meantime I would suggest you to add following snipped to the `Activity` where the player is embedded:
```
@Override
protected void onStop()
{
    this.bitmovinPlayerView.onPause();
    super.onStop();
}
```

**Comment by ravirajjak** [comment]
@matamegger  thanks

**Comment by matamegger** [comment]
@ravirajjak We introduced an `onStop` as well as an `onStart` in version `2.17.0` of the Android SDK.
We highly recommend to call them with the `Activity`s lifecycle callbacks (same as with `onPause` and `onResume`)
