### ISSUE TITLE
On Download Delete issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#27]
@matamegger @LudoMichaud @dweinber 
When I download the video On complete is Triggered also when I delete the video on Complete is triggered. Now the issue is How do I Identify if the video is downloaded or deleted?

**Comment by matamegger** [comment]
I would like to remind you that it is recommended to reach out to our support team support@bitmovin.com , as this is not an issue with the sample apps them self.

That said, the `onCompleted` callback provides you with a `SourceItem` and the current `OfflineContentOptions`, which give you a detailed list on what is downloaded and what not.
Also don't be afraid of looking into the `OfflinePlayback` sample, as we actually have implemented a simple ui, that reacts to the offline state of an item.
