### ISSUE TITLE
No acceptable module found. Local version is 0 and remote version is 0. Conflict with Google Cast SDK

### ISSUE THREAD

**Issue by chebTS** [bitmovin/bitmovin-player-android-samples#33]
**Which sample is this report about?**
- Sample name or link: 
After adding cast SDK on some device we have this issue:

> Caused by: java.lang.RuntimeException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
>         at com.google.android.gms.internal.cast.zze.zzf(Unknown Source:51)
>         at com.google.android.gms.internal.cast.zze.zza(Unknown Source:1)
>         at com.google.android.gms.cast.framework.CastContext.<init>(Unknown Source:37)
>         at com.google.android.gms.cast.framework.CastContext.getSharedInstance(Unknown Source:6)
>         at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:**106**)
>         at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:82)
>         at com.bitmovin.player.BitmovinPlayer.<init>(SourceFile:71)
>         at com.bitmovin.player.BitmovinPlayerView.<init>(SourceFile:134)
>         at com.bitmovin.player.BitmovinPlayerView.<init>(SourceFile:120)

Bug occurs on layout when BitmovinPlayerView created.

```
<com.bitmovin.player.BitmovinPlayerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/bitmovinPlayerView" />
```

After a lot of Googling I found this solution: https://www.e-learn.cn/content/wangluowenzhang/650546
I guess you can add this code in **BitmovinPlayer.class**

```
try {
        CastContext.getSharedInstance(context)
    } catch (e: Exception) {
        // track non-fatal
        return false
    }
```

This bug occurs on different devices of our user.
I reproduced it on Asus Android TV device. Google Play Services version on this device is: 15.0.90 (080706-231259764)

**Comment by chebTS** [comment]
Hey guys, any thoughts about this issue?

**Comment by dweinber** [comment]
Hey @chebTS,
Thanks for reporting this, I've filed an internal issue for this.

**Comment by chebTS** [comment]
@dweinber Thanks. Waiting for this fix.

**Comment by shine-chen** [comment]
Waiting for fix +1

Thanks.

**Comment by manimaran96** [comment]
Waiting for fix +1

**Comment by zack-barakat** [comment]
Hi @dweinber any update on this issue?

**Comment by dweinber** [comment]
Hey @zack-barakat, there is no update I could share so far, sorry.

**Comment by zack-barakat** [comment]
No problem @dweinber 
For anyone who is still having this issue you can avoid it by create the player programmatically and enable or disable casting based on whether the availability of casting in the device.

```
val configuration = PlayerConfiguration()
configuration.remoteControlConfiguration = RemoteControlConfiguration().apply { 
    isCastEnabled = isCastApiAvailable()
}
val bitmovinPlayerView = BitmovinPlayerView(requireContext(), configuration)
```

Extension function to check if casting is available.
```
fun Context.isCastApiAvailable(): Boolean {
    val isCastApiAvailable = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this) == ConnectionResult.SUCCESS
    try {
        CastContext.getSharedInstance(this)
    } catch (e: Exception) {
        e.printStackTrace()
        return false
    }
    return isCastApiAvailable
}
```
