### ISSUE TITLE
Remove downloaded file 

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#34]
**What is your idea for a new sample?**
For example: 
 If user login in Netflix and download the content. The download should be bind with that particular user.
Once user logsout the file should get deleted.
Either it can be a specific file or it can be whole downloaded file.

**Comment by dweinber** [comment]
That should be rather easy to do. On log out of your app, you can reuse the code from the existing offline content sample to delete the content: 

https://github.com/bitmovin/bitmovin-player-android-samples/blob/master/OfflinePlayback/src/main/java/com/bitmovin/player/samples/offline/playback/MainActivity.java#L286

Therefore, I'm not sure this is worth a separate sample.

**Comment by ravirajjak** [comment]
@dweinber  dude 
HomeActivity -> Where user can logs out.
Video Activity-> Where i create a listitem and able to delete video.

So once user downloads the video from VideoActivity and backpress it. No instance of videoActivity will be there.
Now I go back to HomeActivity and press logout button . Than How can I get ListItem?
To create ListItem I need sourceItem to create source item I need MPD and Laurl which I get on VideoActivity.
I hope u understood.
