### ISSUE TITLE
Hide Notification Title

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#36]
**Which sample is this report about?**
- https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/BasicControlNotification

**Describe the bug**
Not able to hide the NotificationTitle

**To Reproduce**
1. Download any video in Offline and Set title to SourceItem.
2.  On Complete of download you will see notification Title

**Expected behavior**
Need custom controls to hide Notification Title

**Smartphone (please complete the following information):**
All

**Comment by matamegger** [comment]
This can be customized by extending the `BitmovinDownloadService`.
