### ISSUE TITLE
Casting Issue

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#38]
**Which sample is this report about?**
- Casting Issue

**Describe the bug**
I created custom source item while casting it shows "No supported technology was detected. Please download the Flash Player from url or try another browser".

**To Reproduce**
1. Create CustomSourceItem extends SourceItem
2. Click on cast button

**Expected behavior**
On Click of cast button it should cast

**Smartphone (please complete the following information):**
 - Device:  Sony Bravia
 - OS:  Oreo
 - Version:

**Comment by dweinber** [comment]
Hi, thanks for reporting this issue. However, it is not related to any of the samples in this repository, so please contact support@bitmovin.com with additional details, like the exact configuration. Thank you for your understanding.

**Comment by ravirajjak** [comment]
@dweinber cmon dude
https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/BasicCasting 

This is the example

**Comment by ravirajjak** [comment]
@dweinber  Please help
