### ISSUE TITLE
Crashes on TV

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#39]
**Which sample is this report about?**
- Crashes Using TV Sample

**Describe the bug**
 Binary XML file line #9: Error inflating class com.bitmovin.player.BitmovinPlayerView
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.bitmovin.player.BitmovinPlayerView

**To Reproduce**
1.  Automatically it crashes

**Expected behavior**
It should not Crash
**Smartphone (please complete the following information):**
 - Device: Sony Bravia
 - OS: 
 - Version:

**Comment by jarhoax** [comment]
@ravirajjak We will have a look. Can you please provide us the exact model and Android OS version? Thanks

**Comment by ravirajjak** [comment]
OS: Nougat
Version :7.0

**Comment by zack-barakat** [comment]
@jarhoax This happens when to all android model I tested so far. The key to reproduce this error is to test bitmovin player with cast libraries added. I had to remove all casting related code to solve this issue. Is a there a way to catch this error.

**Comment by jarhoax** [comment]
Please file a report to support@bitmovin.com. We need to have another look.

**Comment by zack-barakat** [comment]
Thanks @dweinber 
For anyone who is still having this issue you can avoid it by creating the player programmatically and enable or disable casting based on the availability of casting in the device.

```
val configuration = PlayerConfiguration()
configuration.remoteControlConfiguration = RemoteControlConfiguration().apply { 
    isCastEnabled = isCastApiAvailable()
}
val bitmovinPlayerView = BitmovinPlayerView(requireContext(), configuration)
```

Extension function to check if casting is available.
```
fun Context.isCastApiAvailable(): Boolean {
    val isCastApiAvailable = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this) == ConnectionResult.SUCCESS
    try {
        CastContext.getSharedInstance(this)
    } catch (e: Exception) {
        e.printStackTrace()
        return false
    }
    return isCastApiAvailable
}
```
