### ISSUE TITLE
Video forward/backward not working in chrome casting after seeking video from seek bar 

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#41]
**Which sample is this report about?**
- Sample name or link:   bitmovin-player-android-samples (Latest Version: 2.22.0)

**Describe the bug**

Video forward/backward not working in chrome casting after seeking video from seek bar 

**To Reproduce**

1.Start Chrome Casting From mobile
2.seeking video from mobile 
3.click on forward from mobile
4.It goes to the time of before seeking  time

**Expected behavior**
Forward/backward should work properly in chrome casting with defined forward/backward interval 

**Smartphone (please complete the following information):**
 - Device: G8141 (Sony)
 - OS: Oreo
 - Version:8.0.0

**Comment by matamegger** [comment]
Thanks for reaching out @Prashantj007!
I assume you are talking about the `BasicCasting` sample. However, I am not aware of a "forward/backward" button in the sample. Can you please explain in detail what you are referring to?
Also, have you done any changes to the code?
