### ISSUE TITLE
Cannot display subtitle in OfflinePlayback.

### ISSUE THREAD

**Issue by GlausLivio** [bitmovin/bitmovin-player-android-samples#43]
**Which sample is this report about?**
OfflinePlayback

**Describe the bug**

I am adding subtitle tracks with my vtt file url.
But For OfflineSourceItem, subtitle track is not downloaded at the local storage.
I cannot display my subtitle.

**Expected behavior**
Need to be displayed subtitle in Offline play.

**Smartphone (please complete the following information):**
Tested on Android, will check iOS in the future.

**Comment by LudoMichaud** [comment]
Hi @GlausLivio , 
Thanks for reaching out. 
Please could you let me know if the VTT file is present directly in the manifest or via the player API ? 
Also, please feel free to reach out to our support team directly (support@bitmovin.com).
