### ISSUE TITLE
How to interact with Javascript from Android side? 

### ISSUE THREAD

**Issue by lxc7923** [bitmovin/bitmovin-player-android-samples#44]
## Describe the bug

I have some problem with the bitmovin player:

1.My colleague customized the player's UI and added a button in it, and I set it by calling this 2 methods: 
`StyleConfiguration. setPlayerUiCss()` and `StyleConfiguration. setPlayerUiJs().`

2.When I click the button in the player, I want to do something on the android side, but I found no way for interaction between Javascript and Android.(Usually we can define Javascript interfaces when using Webview)

**Comment by matamegger** [comment]
Player API calls work the same way as in the WebSDK (`player.play()` etc.)

If you want to trigger player unrelated code, there is currently no officially supported way of doing so.

**Comment by matamegger** [comment]
We now have support for this, check out our CustomUiSample
