### ISSUE TITLE
Representation downloads can be downloaded in Queue

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#45]
**What is your idea for a new sample?**

Representation downloads can be downloaded in Queue.

**What's the use case behind it?**

Memory Check while Downloading and Resume Download.

 If movie downloading in progress, cancel from the screen it'll get deleted and pick next movie from 
 the queue if queue data available.

**Comment by matamegger** [comment]
Hej @Prashantj007,
I am not quite sure what's it that your are asking for. 

`Representations` (called `OfflineOptionEntry` in the public API) are added to a download queue. By default the queue is processed by multiple threads, but this can be changed in the `OfflineConfiguration`. Also the SDK detects if the device is out of space and will send an `ErrorEvent` through the `OfflineContentManagerListener`.

Does this answer your question? Or are you requesting an sample, showing how to set the paralellization count? 
Also feel free to contact support@bitmovin.com
