### ISSUE TITLE
Last few seconds content is not playing in offline mode for downloaded video

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#47]
**Which sample is this report about?**

- Sample name : offline playback

-Sample link: https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/OfflinePlayback

**Describe the bug**

In the latest SDK version 2.25.0, we are facing the problem of downloaded content unable to play in offline in the last few seconds of every content.

Same issue is found in the latest sample code provided.

**To Reproduce**

1. Download the content 
2. Play downloaded content in offline mode
3. unable to play content in last few seconds it showing a loader

**Expected behavior**
Downloaded content should be played in offline completely.

**Smartphone (please complete the following information):**
 - Device: All Devices
 - OS: Android
 - Version: All

Please check this issue and do the needful changes, Your immediate reply will be highly appreciated.

**Comment by matamegger** [comment]
We could not reproduce this with our sample content.

For further assistance we would like to ask you to provide us the stream(s) you are seeing this problem.
If you don't want to share them publicly, please provide us them over: support@bitmovin.com

Thanks!

**Comment by Prashantj007** [comment]
@matamegger Thanks for replying.

To Reproduce this issue please follow the below steps:
Steps to reproduce the behavior:

1. Download the content
2. Play downloaded content in offline mode
3. Unable to play content in the last few seconds it showing a loader

We are using the following stream and we not changed any code in the sample.

https://bitmovin-a.akamaihd.net/content/MI201109210084_1/mpds/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.mpd

Device: All Devices
OS: Android
Version: All

### Expected behavior
Downloaded content should be played in offline completely.

Please kindly check and let us know if you need anything from our side.

**Comment by matamegger** [comment]
The Team found the potential bug and will include a fix in an upcoming release!

Thanks for reporting!

**Comment by qzzzzzzzzzzz** [comment]
The stable new release of Bitmovin player is 2.25.1 right? The issue is still persist on that release.Previous versions like 2.24.0 is working fine while playing offline content.

**Comment by Prashantj007** [comment]
Yes. This issue available in the new release of Bitmovin player is 2.25.1.

**Comment by matamegger** [comment]
We are aware of the issue. And we will fix this in an upcoming release.
