### ISSUE TITLE
Offline Playback

### ISSUE THREAD

**Issue by sreedev-pr** [bitmovin/bitmovin-player-android-samples#48]
**Which sample is this report about?**
- Sample name or link: 
https://github.com/bitmovin/bitmovin-player-android-samples/tree/master/OfflinePlayback
**Describe the bug**
Offline playback of drm content provided in the sample. I cannot play the last few seconds of the video during offline playback.

**To Reproduce**
1. Download the sample drm content video.
2. Try the offline playback.

**Expected behavior**
The video was expected to be played without issues, but I cannot play the last few seconds of the video.

**Smartphone (please complete the following information):**
 - Device: Redmi 4, Google Pixel 3 XL
 - OS: 7,8
 - Version:

**Additional context**
This is the logcat error
android.media.MediaDrm$MediaDrmStateException: Failed to get key request

**Comment by matamegger** [comment]
Thanks for reporting!
This issue is already tracked internally, and a fix will be included in an upcoming release.

**Comment by matamegger** [comment]
This issue has been fix already.
