### ISSUE TITLE
Not able to set Duration of a Player

### ISSUE THREAD

**Issue by ravirajjak** [bitmovin/bitmovin-player-android-samples#5]
In  your sample code of Custom UI. You guys are using time shift and duration of a player.
How unfortunate that you guys didnt allow to set duration.
If my need is to seek to a x duration I am not able to do it.

**Comment by matamegger** [comment]
I am afraid I do not understand what you are trying to do? Can you please provide us more details?

For VoD content the API methods `getDuration()` and `seek(...)` must be used. Where you can use `seek` to go to the specified position in the media (in seconds).
For live content the API methods `getMaxTimeShift()` and `timeShift(...)` must be used. Where the parameter given to `timeShift()` must be between `getMaxTimeShift()` (negative number) and zero.
Additionally, `timeShift(...)` can also take a unix timestamp.

**Comment by jarhoax** [comment]
@ravirajjak Does this issue still exist or were you able to resolve it?

**Comment by ravirajjak** [comment]
Thanks its working using player.seek(seconds)
