### ISSUE TITLE
Play video with MPEG-CENC DRM on android 

### ISSUE THREAD

**Issue by junburg** [bitmovin/bitmovin-player-android-samples#50]
Hi. I have a question about MPEG-CENC DRM on Android. We encoded the video using MPEG-CENC DRM and finished uploading it to the server. And We want to use the Player SDK to stream on Android devices. However, We are having difficulty because We can't find any references or codes related to this. (**https://bitmovin.com/docs/player/tutorials/how-to-play-mpeg-cenc-clearkey-content** This page is the most relevant, but not the way to use the Android player SDK.) How can I play and control video files encoded in MPEG-CENC and uploaded to the server via the Android Player SDK for streaming? I would appreciate it if you could provide any reference material or code.

I have a one more question. After downloading the MPEG-CENC encoded video file, How to play back and control video using player SDK? I would appreciate it if you could provide any reference material or code.

Thank you.

**Comment by matamegger** [comment]
Sorry for the delayed answer. This repository is not meant for regular support questions. But this email is: support@bitmovin.com

However, Clearkey is currently not supported by the android SDK. If you have Widevine CENC content, it is supported! Have a look into the `BasicDRM` sample.
A tutorial on our offline feature can be found here: https://bitmovin.com/docs/player/tutorials/offline-playback-with-the-bitmovin-android-sdk
