### ISSUE TITLE
Download completed status displayed in notification if cancel movie from downloading state

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#51]
**Which sample is this report about?** Offline Playback
- Sample name or link:  Offline Playback (Version **2.25.2**)

**Describe the bug**
Download completed status displayed in the notification if cancel movie from downloading state

**To Reproduce**
1. Start the downloading
2. downloading progress
3. cancel downloading
4. observe the notification 
5. shows download complete

**Expected behavior**
Download the complete notification display only when the download is completed.

**Smartphone (please complete the following information):**
Device: All Devices
OS: Android
Version: All

**Comment by matamegger** [comment]
The offline feature got some improvements since you reported this issue.

Are you still seeing this in the most recent player version (`2.29.0`)?

**Comment by nicolasjafelle** [comment]
@matamegger I can confirm this still happening in latest `2.32.0` build.
