### ISSUE TITLE
While Downloading Content Sometimes returns SUSPENDED State.

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#52]
**Which sample is this report about?** Offline Playback
- Sample name or link:  Offline Playback (Version: 2.25.2)

**Describe the bug**
While Downloading Content Sometimes returns SUSPENDED State but downloading still continues so on progress method didn't call and when a download gets completed it returns
DOWNLOAD COMPLETE.

**To Reproduce**
1. We are maintaining multiple content download requests into Queue.
2. While downloding next queue content programmatically sometimes it returns SUSPENDED state so It gives problem to download content in Queue programmatically.

**Expected behavior**
If any content is Downloading then state should be DOWNLOADING.

**Smartphone (please complete the following information):**
 - Device: All
 - OS: Android
 - Version: All

**Comment by matamegger** [comment]
We implemented some improvements to the offline feature since you reported this issue.

Are you still seeing this behavior in the most recent player version `2.29.0`?

**Comment by Prashantj007** [comment]
Yes .This issue available on 2.29.0 version.

If I download multiple contents simultaneously after some time I checked one of content it getting pause automatically state returns suspended it should be downloading state.

**Comment by matamegger** [comment]
Thanks!

Could you provide us a walking skeleton with you workflow? 
You can send it to support@bitmovin.com

**Comment by Prashantj007** [comment]
This issue available on the 2.37.0 version.

If I download multiple contents simultaneously after some time I checked one of the content it getting pause automatically state returns suspended it should be downloading state.
