### ISSUE TITLE
Hide download status notification completely

### ISSUE THREAD

**Issue by sreedev-pr** [bitmovin/bitmovin-player-android-samples#53]
**What is your idea for a new sample?**

**What's the use case behind it?**

**Comment by sreedev-pr** [comment]
I do not want the downloading status to be shown as it behaves inconveniently

**Comment by matamegger** [comment]
While it is not possible to completely hide the Notification. (It is needed to bind the background service to it, because else the system could kill the process).

However, it is possible to override the `BitmovinDownloadService` and it's method `getForegroundNotification`, to customize the Notification in it's behaviour and look.

Also, in order to improve our default behaviour, I would like to ask you how you would expect it to behave :) (Either here, or via email support@bitmovin.com)

Thanks!

**Comment by sreedev-pr** [comment]
> While it is not possible to completely hide the Notification. (It is needed to bind the background service to it, because else the system could kill the process).
> 
> However, it is possible to override the `BitmovinDownloadService` and it's method `getForegroundNotification`, to customize the Notification in it's behaviour and look.
> 
> Also, in order to improve our default behaviour, I would like to ask you how you would expect it to behave :) (Either here, or via email [support@bitmovin.com](mailto:support@bitmovin.com))
> 
> Thanks!

Hi,
The download deletion event causes the download manager to reach the onCompleted callback and download completed notification is seen.
I would like to hide that.

**Comment by matamegger** [comment]
In this case I want to highlight the possibility of overriding the `BitmovinDownloadService` and in particular the `onTaskStateChanged` method.
Except for the progress Notification, all Notifications are generated and fired in this method, so by overriding it, you can implement your wished behaviour.

**Comment by sreedev-pr** [comment]
> In this case I want to highlight the possibility of overriding the `BitmovinDownloadService` and in particular the `onTaskStateChanged` method.
> Except for the progress Notification, all Notifications are generated and fired in this method, so by overriding it, you can implement your wished behaviour.

Could you provide a sample for this ? It would be very helpful.

**Comment by stonko1994** [comment]
Just create a custom class which extends the `BitmovinDownloadService` and override the `onTaskStateChanged` method:

```java
public class AwesomeDownloadService extends BitmovinDownloadService
{
  …
  @Override
  protected void onTaskStateChanged(DownloadManager.TaskState taskState)
  { ... }
}
```

And set it to the `OfflineContentManager` in your activity or elsewhere:

```java
OfflineContentManager.setDownloadServiceClass(AwesomeDownloadService.class);
```
