### ISSUE TITLE
Unable to play CBCS encrypted fMP4 file using DASH manifest 

### ISSUE THREAD

**Issue by Apurva712** [bitmovin/bitmovin-player-android-samples#58]
**Sample:** 

## Describe the bug
I am trying to play an encrypted fmp4 file which is encrypted using CBCS scheme. I have a DASH manifest and a Widevine license URL. I am using basicDRMplayback project. After feeding the stream url and  license url the player is just getting stuck without giving any error.

## Behavior
**Actual:** The player is just getting stuck without giving any error.
**Expected:** The player should be able to decrypt the video and able to playback.

## How to reproduce
**Steps:**

1. 
2. 
3.

**Comment by matamegger** [comment]
Thanks for reaching out!

In order to resolve your issue, it would be helpful if you could provide us your sample stream.
Don't hesitate to reach out to: support@bitmovin.com

**Comment by Apurva712** [comment]
Thanks for your response. I am closing this issue as there were few issues in the stream. After fixing them I am able to playback the content.

**Comment by matamegger** [comment]
Great! Glad to hear that.
