### ISSUE TITLE
Basic Ads Sample Not Working(License Error)

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#60]
**Sample:** Basic Ads
 Version 2.37.0

## Describe the bug
1.Run The Basic Ad demo 
2.With Proper License Key
3.Showing License Error.

If I am using the same license key with another demo like offline playback is working fine. 

## Behavior
**Actual:** License error showing if I enter the valid license key.
**Expected:** Play content properly.

**Comment by matamegger** [comment]
Thanks for reaching out!
Could you please verify that you have added the package name of the sample to your license?
For the BasicAds sample this should be `com.bitmovin.player.samples.ads.basic`

**Comment by Prashantj007** [comment]
Yes.Its Same.

**Comment by matamegger** [comment]
We can not reproduce this behaviour on our side.

Please contact: support@bitmovin.com

**Comment by fhugoduarte** [comment]
@matamegger Hello!
I'm developing an app with react-native and created a module based on the BasicPlayback example. I added the key to the meta-data and added the package to the license. But I still get the license error (code: 1016), do you know what may be happening?

**Comment by matamegger** [comment]
Hello @fhugoduarte,

Just to be sure. When referring to "package" we are talking about the app identifier i.e. the value in the `<manifest package="this value">` in your `AndroidManifest.xml`

If you still encounter issues please reach out to support@bitmovin.com

**Comment by matamegger** [comment]
Have you ensured that you added the license in the `AndroidManifest.xml` of your react native project?
(In the project you linked, it is not entered, which makes sense as you don't want to share this publicly)

We generally tested react native setups without problems.

**Comment by fhugoduarte** [comment]
Thx for the support and forgiveness for the late reply.
After a while analyzing the errors, I found that, for some reason, a **.** at the end of the package name. Thx for all.

**Comment by matamegger** [comment]
@fhugoduarte 
Great you could solve this!

@Prashantj007 
Could you also please double check, that all information are coherent?
