### ISSUE TITLE
preprocessHttpRequest is not called

### ISSUE THREAD

**Issue by fhugoduarte** [bitmovin/bitmovin-player-android-samples#61]
**Describe the bug**

I need to add some header to the request, but the preprocessHttpRequest method is not called.

**Additional context**

I'm using the bitmovin player in a react-native app. It's working fine, but I need to change the request header and I'm trying to implement the preprocessHttpRequest method to do this. However, the method is not called.

Here is a short code snippet of how I'm trying to do this implementation.

```java
public class RNBitmovinPlayerManager extends SimpleViewManager<BitmovinPlayerView> implements PreprocessHttpRequestCallback {

    @Override
    public BitmovinPlayerView createViewInstance(ThemedReactContext context) {
        BitmovinPlayerView bitmovinPlayerView = new BitmovinPlayerView(context);
        BitmovinPlayer bitmovinPlayer = bitmovinPlayerView.getPlayer();

        PlayerConfiguration playerConfiguration = new PlayerConfiguration();
        NetworkConfiguration networkConfiguration = new NetworkConfiguration();

        networkConfiguration.setPreprocessHttpRequestCallback(this);
        playerConfiguration.setNetworkConfiguration(networkConfiguration);

        playerConfiguration.setSourceItem("url");

        bitmovinPlayer.setup(playerConfiguration);

        return bitmovinPlayer;
    }

    @Nullable
    @Override
    public Future<HttpRequest> preprocessHttpRequest(HttpRequestType httpRequestType, HttpRequest httpRequest) {
      return null;
    }
}
```

I haven't found any examples of implementation and other interfaces like **FullscreenHandler** and **LifecycleEventListener** work well, is there any kind of specific request that calls this method?

I'm using the example video: https://bitmovin-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by matamegger** [comment]
Hello @fhugoduarte ,

What player version are you using?

**Comment by fhugoduarte** [comment]
@matamegger, **2.37.0**.

I'm using this fork, if you want to take a look: https://github.com/fhugoduarte/react-native-bitmovin-player/blob/master/android/build.gradle#L34

**Comment by matamegger** [comment]
I see. 
Currently the callback only supports DRM calls. May I ask what type of HTTP request you want to manipulate?
I will update our internal issue tracking accordingly.

**Comment by fhugoduarte** [comment]
@matamegger I need to handle the request that the player makes to get the AES-128 key.
Because we work with our own server and we need to generate a token to get the key.

have any solution for that?

**Comment by jpdemagalhaes** [comment]
Just to add on @fhugoduarte's reply. This already works on any Android browser, we can manipulate each HTTP request the player makes, so there's no apparent reason that it should not work on the SDK.

Also, this token that we need to generate, we have to do it on each request, because this token is a one-way use only, and it expires.

**Comment by atakankersit** [comment]
Hi,
I have same problem with @fhugoduarte. We want to add header before http request. That’s why We are trying to use Network configuration. But I think there is a bug about network configuration. Because “setPreprocessHttpRequestCallback” callback never called. You can see my code at below. Can you help us?
```
val networkConfiguration  = NetworkConfiguration()
      networkConfiguration.setPreprocessHttpRequestCallback { httpRequestType, httpRequest ->
        val x = object : Future<HttpRequest> {
          override fun isDone(): Boolean {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
          }
          override fun get(): HttpRequest {
            val headers = (httpRequest.headers ?: hashMapOf()).apply {
              put("testKey", "testValue")
            }
            httpRequest.headers = headers
            return httpRequest
          }

          override fun get(timeout: Long, unit: TimeUnit): HttpRequest {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
          }

          override fun cancel(mayInterruptIfRunning: Boolean): Boolean {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
          }

          override fun isCancelled(): Boolean {
            TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
          }

        }
        return@setPreprocessHttpRequestCallback x
      }
```

And We have added to NetworkConfiguration to PlayerConfiguration.

      val playerConfig = PlayerConfiguration()
      playerConfig.remoteControlConfiguration = remoteControlConfig
      playerConfig.styleConfiguration = styleConfig
      playerConfig.sourceConfiguration = sourceConfig
      playerConfig.playbackConfiguration = playbackConfig
      playerConfig.networkConfiguration=networkConfiguration
