### ISSUE TITLE
How can I play dash format with clear key

### ISSUE THREAD

**Issue by abhishekvuclip** [bitmovin/bitmovin-player-android-samples#62]
How can I play dash format with clear key ?
The basic dash sample does not seem to have clear key dash url but a simple one, when i try to play the clear key dash/mpd url, it only shows subtitle but there is no video/audio.

At the same time if I play HLS/m3u8, it plays fine.

**Comment by dweinber** [comment]
Hey @abhishekvuclip,
You will need to provide a [ClearKeyConfiguration](https://bitmovin.com/docs/player/api-reference/android/android-sdk-api-reference-v2#/player/android/2/docs/com/bitmovin/player/config/drm/ClearKeyConfiguration.html) which specifies the KID and keys, which are used to decrypt.

In case of HLS, the keyfile is linked per specification in the playlist file, but this is not the case for DASH.
