### ISSUE TITLE
Subtitle Displaying On Top(Mobile/Android TV)

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#64]
**Which sample is this report about?**
- Sample name or link: BasicDRMplayback

**Describe the bug**
1.Play movie 
2.Select Subtitle 
3.observe the subtitle displaying on top of the movie

**To Reproduce**
1.Play movie 
2.Select Subtitle 
3.observe the subtitle displaying on top of the movie

**Expected behavior**
The subtitle should be displayed on the bottom.

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Version:All

**Additional context**
 If you added some callback from changing subtitle position just let us know we are not getting the actual function to change subtitle position.

**Comment by matamegger** [comment]
We are already tracking this internally.

Once this is fix, we will inform you here.

**Comment by zack-barakat** [comment]
Hi @matamegger Any update on this.

**Comment by matamegger** [comment]
Hi @zack-barakat and @Prashantj007 ,

in our last release we fixed an issue with TTML subtitles where the `origin` and `extend` properties 
 are missing. 
[Release Notes 2.43.0](https://bitmovin.com/docs/player/releases/android/android-2-43-0)

Additionally in the previous release we changed the default values for positioning, if we do not detect them in the source.
[Release Notes 2.42.0](https://bitmovin.com/docs/player/releases/android/android-2-42-0)

In case you are still having trouble with the positioning, please let us know! Preferable over support@bitmovin.com
