### ISSUE TITLE
AVOD is not working on android TV its working on amazon firestick and mobile

### ISSUE THREAD

**Issue by Prashantj007** [bitmovin/bitmovin-player-android-samples#65]
**Which sample is this report about?**
- Sample name or link: 
Ads
**Describe the bug**

1.play movie for pre-roll ads working on amazon firestick but not working on android TV

**Expected behavior**

it should be play ads on android TV
**Smartphone (please complete the following information):**
 - Device: ALL(Android TV)
 - OS: ALL
 - Version:ALL

**Additional context**

**Comment by matamegger** [comment]
I can confirm that pre-roll ads are not playing on a MiBox3.

We will update this issue once the problem is fixed.

**Comment by Prashantj007** [comment]
@matamegger  Any update on this???

**Comment by matamegger** [comment]
We track this issue internally. 
As already mentioned in other threads, feel free to reach out to support@bitmovin.com

**Comment by Prashantj007** [comment]
@matamegger  Any Update On this...Please let me know
