### ISSUE TITLE
Can't handle errors from the response

### ISSUE THREAD

**Issue by nasko700** [bitmovin/bitmovin-player-android-samples#66]
Hello!
It exists PreprocessHttpRequestCallback, but there is no PreprocessHttp**Response**Callback for Android. I need to to handle the errors from the response. Could you add this method in the next version of Bitmovin for Android or give me some steps how to do it without it?
Thank you in advance!

**Comment by matamegger** [comment]
For feature requests and general support please contact: support@bitmovin.com
