### ISSUE TITLE
BitmovinPlayerView not working on Android 5.0

### ISSUE THREAD

**Issue by diemer** [bitmovin/bitmovin-player-android-samples#67]
**Which sample is this report about?**
- Sample name or link: 
BasicPlayback
**Describe the bug**
Trying to use the BitmovinPlayerView on an API 22 device crashes with the following Exception: Error inflating class com.bitmovin.player.BitmovinPlayerView
**To Reproduce**
1. Create an Android API 22 device ( I made an emulator using Galaxy Nexus and API 22)
2. Build and launch the BasicPlayback sample

**Expected behavior**
The sample app launches without any crash.

**Smartphone (please complete the following information):**
 - Device: Huawei P8 Lite, Android Emulator
 - OS: Android
 - Version: 5.0

**Additional context**
I discovered this issue via the pre-launch report on the Play Store on our app. I decided to see if it was just something specific to our implementation, so I created an Android 5.0 device matching the screen resolution and API level of the failing test. It turns out it's not us and the sample exhibits the same behavior.

According to [this page](https://bitmovin.com/docs/player/articles/device-and-cross-browser-support) Android 5.0 should still be supported.

**Comment by matamegger** [comment]
Thanks for reaching out!

We could verify your observation. This is most likely cause by a current bug in `androidx.appcompat:appcompat` regarding `WebView`s
In our testing we could verify that with version `1.2.0-beta01` of the `appcompat` library, this issues got fixed.
As the date of a stable release of `appcompat` is not known, we will track this internally.

**Comment by jarhoax** [comment]
@diemer Does this issue still exist?

**Comment by SInCE** [comment]
For further assistance please feel free to reach out to our support team as described here: https://github.com/bitmovin/bitmovin-player-android-samples#support 

Thank you very much for your understanding!
