### ISSUE TITLE
Crash observed while using Bitmovin SDK for Android devices

### ISSUE THREAD

**Issue by khushank9** [bitmovin/bitmovin-player-android-samples#68]
I was trying to build my own application using the Bitmovin SDK. With following library dependencies :
com.bitmovin.player:playercore:2.42.0
androidx.appcompat:appcompat:1.1.0
But whenever open the player activity , It gets crashed.

**Description**

Crash is being observed when App tries to inflate the Bitmovin Player view defined in the Player Activity file.

**To Reproduce**
1. Build the standalone Application with bitmovin dependancies defined above
2.  Try to play a content / or open the player activity
3. Observe the crash.

**Expected behavior**

Crash should not happen as I'm using the same library dependencies as that of BasicDRMPlayback Module from Github repo. 
**Smartphone (please complete the following information):**
 - Device: One Plus 6t
 - OS: Android 10
 - Version: Android 10

**Additional context**

Please check the crash logs here

https://drive.google.com/open?id=1KHY-hrvv9rXxQscH_z5A1NIdrImzZRvw

Following is the XML Class file 
```
[](<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".PlayerActivity">

    <com.bitmovin.player.BitmovinPlayerView
        android:id="@+id/bitmovinPlayerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentStart="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true">
    </com.bitmovin.player.BitmovinPlayerView>


</RelativeLayout>)
```

**Comment by jarhoax** [comment]
https://github.com/bitmovin/bitmovin-player-android-samples/issues/67#issuecomment-613947367

**Comment by jarhoax** [comment]
Got handled already with your support ticket.
