### ISSUE TITLE
Unresolveable class in CustomUiKotlin example

### ISSUE THREAD

**Issue by Foxtur** [bitmovin/bitmovin-player-android-samples#69]
**Which sample is this report about?**
- CustomUIKotlin

**Describe the bug**
After cloning the repository and importing it in Android Studio and opening the CustmUiKotlin project the imported class "com.bitmovin.player.ui.FullScreenUtil" can not be resolved

**To Reproduce**
1. Check out repository
2. Import project in Android Studio
3. Open CustomFullScreenHandler.kt File in CustomUiKotlin example
4. See Linter warning that com.bitmovin.player.ui.FullscreenUtil can't be resolved and build fails

**Expected behavior**
Class should be resolveable

**Additional context**
Android Studio 3.6.2
The FullScreenUtil class can be resolved in the Java version of the example "CustomFullScreenHandler.java"

**Comment by matamegger** [comment]
Hello @Foxtur, thanks for reaching out!
We just fixed the problem.
