### ISSUE TITLE
Impact of Bintray shutdown on the Android Player SDK library

### ISSUE THREAD

**Issue by Marc-JB** [bitmovin/bitmovin-player-android-samples#75]
JFrog announced that Bintray will shutdown on May 1st: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/. Will this impact the distribution of the Android Player SDK library, since it's available from `bitmovin.bintray.com`? If so, will this library (including older versions of this library) be available on other solutions, like Maven Central?

**Comment by jarhoax** [comment]
This will definitely impact our current distribution. We are working on a transfer plan and will update here as soon as we have more information.

**Comment by SInCE** [comment]
For further assistance please feel free to reach out to our support team, as described here: https://github.com/bitmovin/bitmovin-player-android-samples#support 

Thank you very much for your understanding!
